### ISSUE TITLE
Error: Cannot find module 'node:crypto'

### ISSUE THREAD

**Issue by kevev** [synclounge/synclounge#1797]
**System Details**

- Ubuntu 22.04.4 LTS

### Self-Hosting
Yes

**System Details**
Node v12.22.9

**SyncLounge Details**
5.2.30

- Running in Docker?: No

### Issue information

Error: Cannot find module 'node:crypto'
Require stack:
- /usr/local/lib/node_modules/synclounge/node_modules/uuid/dist/rng.js
- /usr/local/lib/node_modules/synclounge/node_modules/uuid/dist/v1.js
- /usr/local/lib/node_modules/synclounge/node_modules/uuid/dist/index.js
- /usr/local/lib/node_modules/synclounge/node_modules/syncloungeserver/dist/socketserver/state.js
- /usr/local/lib/node_modules/synclounge/node_modules/syncloungeserver/dist/socketserver/handlers.js
- /usr/local/lib/node_modules/synclounge/node_modules/syncloungeserver/dist/socketserver/index.js
- /usr/local/lib/node_modules/synclounge/node_modules/syncloungeserver/dist/lib.js
- /usr/local/lib/node_modules/synclounge/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:85:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/synclounge/node_modules/uuid/dist/rng.js:7:42)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/synclounge/node_modules/uuid/dist/rng.js',
    '/usr/local/lib/node_modules/synclounge/node_modules/uuid/dist/v1.js',
    '/usr/local/lib/node_modules/synclounge/node_modules/uuid/dist/index.js',
    '/usr/local/lib/node_modules/synclounge/node_modules/syncloungeserver/dist/socketserver/state.js',
    '/usr/local/lib/node_modules/synclounge/node_modules/syncloungeserver/dist/socketserver/handlers.js',
    '/usr/local/lib/node_modules/synclounge/node_modules/syncloungeserver/dist/socketserver/index.js',
    '/usr/local/lib/node_modules/synclounge/node_modules/syncloungeserver/dist/lib.js',
    '/usr/local/lib/node_modules/synclounge/server.js'
  ]
}

**Describe your bug/issue**
I am not sure if an update of Node did this or if the latest version of Synclounge did this.

The app does not start.

**Comment by kevev** [comment]
I removed the OS version of node and installed the latest node from git and all is good.
